fix incorrect segment comprehension

diff --git a/sbr b/sbr
--- a/sbr
+++ b/sbr
@@ -1,5 +1,6 @@
 #!/bin/bash
-set -eu -o pipefail
+set -euE -o pipefail
+trap 'echo "${0##*/}: failed @ line $LINENO: $BASH_COMMAND"' ERR
 
 main()
 {
@@ -43,30 +44,29 @@ bin()
 fs()
 {
 	local cmd=$1 path=$2
-	case $path in
-		docker-volume:*|dv:*)
-			IFS=$'\n' read -d '' -ra seg <<< "${path//:/$'\n'}"
-			volume=${seg[0]}
-			path=${seg[1]:-}
+	IFS=$'\n' read -d '' -ra seg <<< "${path//:/$'\n'}" ||:
+	case ${seg[0]} in
+		docker-volume|dv)
+			volume=${seg[1]}
+			path=${seg[2]:-}
 			if ! docker volume inspect -- "$volume" >/dev/null 2>&1; then
 				echo "'$volume': no such docker volume" >&2
 				exit 1
 			fi
 			call "fs/docker-volume/$cmd" "$volume" ${path:+"$path"}
 		;;
-		rclone:*)
-			path=${path#*:}
+		rclone)
+			path=${seg[1]}
 			call "fs/rclone/$cmd" "$path"
 		;;
-		mariadb-docker:*|mdbd:*)
-			IFS=$'\n' read -d '' -ra seg <<< "${path//:/$'\n'}"
-			container=${seg[0]}
-			database=${seg[1]}
-			optfile=${seg[2]:-}
+		mariadb-docker|mdbd)
+			container=${seg[1]}
+			database=${seg[2]}
+			optfile=${seg[3]:-}
 			call "fs/mariadb-docker/$cmd" "$container" "$database" ${optfile:+"$optfile"}
 		;;
-		local:*)
-			path=${path#*:}
+		local)
+			path=${seg[1]}
 			call "fs/local/$cmd" "$path"
 		;;
 		*)
