improve failure message

diff --git a/sbr b/sbr
--- a/sbr
+++ b/sbr
@@ -122,7 +122,7 @@ call()
 		exists|is-*|*-is-*) ;;
 		*)
 			if [[ $code -ne 0 ]]; then
-				echo "command failed: ${cmd##*/}" >&2
+				echo "command failed: sbr ${cmd##*/} $*" >&2
 				exit $code
 			fi
 	esac
